In [1]:
import pandas as pd

api_df = pd.read_csv("books_api_raw.csv")
scraped_df = pd.read_csv("books_scraped_clean.csv")

print("API dataset shape:", api_df.shape)
print("Scraped dataset shape:", scraped_df.shape)

API dataset shape: (3000, 9)
Scraped dataset shape: (169, 10)

In [2]:
print("API columns:")
print(api_df.columns.tolist())

print("\nScraped columns:")
print(scraped_df.columns.tolist())

print("\nAPI first 5 rows:")
display(api_df.head())

print("\nScraped first 5 rows:")
display(scraped_df.head())

API columns:
['author_name', 'edition_count', 'first_publish_year', 'key', 'number_of_pages_median', 'title', 'ratings_average', 'ratings_count', 'genre']

Scraped columns:
['title', 'title_clean', 'author', 'language', 'publication_year', 'decade', 'sales_millions', 'wiki_genre', 'genre_raw', 'sales_text']

API first 5 rows:

,author_name,edition_count,first_publish_year,key,number_of_pages_median,title,ratings_average,ratings_count,genre
0,['Lewis Carroll'],3547,1865,/works/OL138052W,133.0,Alice's Adventures in Wonderland,4.043859,228.0,fantasy
1,['Charles Dickens'],3196,1843,/works/OL32466W,114.0,A Christmas Carol,3.948718,117.0,fantasy
2,['Oscar Wilde'],3012,1890,/works/OL8193416W,246.0,The Picture of Dorian Gray,4.170543,129.0,fantasy
3,['Daniel Defoe'],2420,1686,/works/OL45089W,274.0,Robinson Crusoe,4.000000,29.0,fantasy
4,['L. Frank Baum'],2049,1899,/works/OL18417W,159.0,The Wonderful Wizard of Oz,3.953488,129.0,fantasy

Scraped first 5 rows:

,title,title_clean,author,language,publication_year,decade,sales_millions,wiki_genre,genre_raw,sales_text
0,A Tale of Two Cities,a tale of two cities,Charles Dickens,English,1859,1850,200.0,historical fiction,Historical fiction,>200 million
1,The Little Prince,the little prince,Antoine de Saint-Exupéry,French,1943,1940,200.0,fantasy,Fantasy,200 million
2,The Alchemist,the alchemist,Paulo Coelho,Portuguese,1988,1980,150.0,fantasy,Fantasy,150 million
3,Harry Potter and the Philosopher's Stone,harry potter and the philosophers stone,J. K. Rowling,English,1997,1990,120.0,fantasy,Fantasy,120 million
4,And Then There Were None,and then there were none,Agatha Christie,English,1939,1930,100.0,mystery,Mystery,100 million

In [3]:
print("=== API DATASET ===")

print("\nMissing values:")
print(api_df.isnull().sum())

print("\nDuplicate rows:", api_df.duplicated().sum())

print("\nData types:")
print(api_df.dtypes)


print("\n=== SCRAPED DATASET ===")

print("\nMissing values:")
print(scraped_df.isnull().sum())

print("\nDuplicate rows:", scraped_df.duplicated().sum())

print("\nData types:")
print(scraped_df.dtypes)

=== API DATASET ===

Missing values:
author_name                0
edition_count              0
first_publish_year         0
key                        0
number_of_pages_median     9
title                      0
ratings_average           66
ratings_count             66
genre                      0
dtype: int64

Duplicate rows: 0

Data types:
author_name                object
edition_count               int64
first_publish_year          int64
key                        object
number_of_pages_median    float64
title                      object
ratings_average           float64
ratings_count             float64
genre                      object
dtype: object

=== SCRAPED DATASET ===

Missing values:
title                0
title_clean          0
author               0
language             0
publication_year     0
decade               0
sales_millions       0
wiki_genre          44
genre_raw           44
sales_text           0
dtype: int64

Duplicate rows: 0

Data types:
title                object
title_clean          object
author               object
language             object
publication_year      int64
decade                int64
sales_millions      float64
wiki_genre           object
genre_raw            object
sales_text           object
dtype: object

In [4]:
print("Missing values:")
print(scraped_df.isnull().sum())

print("\nDuplicate rows:")
print(scraped_df.duplicated().sum())

print("\nData types:")
print(scraped_df.dtypes)

Missing values:
title                0
title_clean          0
author               0
language             0
publication_year     0
decade               0
sales_millions       0
wiki_genre          44
genre_raw           44
sales_text           0
dtype: int64

Duplicate rows:
0

Data types:
title                object
title_clean          object
author               object
language             object
publication_year      int64
decade                int64
sales_millions      float64
wiki_genre           object
genre_raw            object
sales_text           object
dtype: object

In [5]:
api_clean = api_df.copy()
scraped_clean = scraped_df.copy()

print("API shape before cleaning:", api_clean.shape)
print("Scraped shape before cleaning:", scraped_clean.shape)

API shape before cleaning: (3000, 9)
Scraped shape before cleaning: (169, 10)

In [6]:
scraped_clean["wiki_genre"] = scraped_clean["wiki_genre"].fillna("unknown")
scraped_clean["genre_raw"] = scraped_clean["genre_raw"].fillna("unknown")

print(scraped_clean[["wiki_genre", "genre_raw"]].isnull().sum())

wiki_genre    0
genre_raw     0
dtype: int64

In [7]:
api_clean["title_clean"] = (
    api_clean["title"]
    .str.lower()
    .str.replace(r"[^\w\s]", "", regex=True)
    .str.strip()
)

print(api_clean[["title", "title_clean"]].head(10))

                              title                      title_clean
0  Alice's Adventures in Wonderland  alices adventures in wonderland
1                 A Christmas Carol                a christmas carol
2        The Picture of Dorian Gray       the picture of dorian gray
3                   Robinson Crusoe                  robinson crusoe
4        The Wonderful Wizard of Oz       the wonderful wizard of oz
5                   Treasure Island                  treasure island
6                           Dracula                          dracula
7                Gulliver's Travels                gullivers travels
8              The Call of the Wild             the call of the wild
9                 The Secret Garden                the secret garden

In [8]:
matches = api_clean[
    api_clean["title_clean"].isin(scraped_clean["title_clean"])
]

print("Matching books:", len(matches))

display(
    matches[
        ["title", "author_name", "first_publish_year"]
    ].head(20)
)

Matching books: 105

,title,author_name,first_publish_year
0,Alice's Adventures in Wonderland,['Lewis Carroll'],1865
13,The Wind in the Willows,['Kenneth Grahame'],1908
14,Anne of Green Gables,['Lucy Maud Montgomery'],1908
62,The Hobbit,['J.R.R. Tolkien'],1937
88,Harry Potter and the Philosopher's Stone,['J. K. Rowling'],1997
113,Harry Potter and the Chamber of Secrets,['J. K. Rowling'],1998
141,Charlie and the Chocolate Factory,['Roald Dahl'],1964
156,Charlotte's Web,['E. B. White'],1952
174,Matilda,['Roald Dahl'],1988
191,James and the Giant Peach,['Roald Dahl'],1961
209,Dune,['Frank Herbert'],1965
219,The Hunger Games,['Suzanne Collins'],2008
234,Where the Wild Things Are,['Maurice Sendak'],1963
240,Catching Fire,['Suzanne Collins'],2009
249,Watership Down,"['Richard Adams', 'Richard Adams']",1972
257,The Giver,['Lois Lowry'],1993
258,A Wrinkle in Time,"[""Madeleine L'Engle""]",1962
300,Alice's Adventures in Wonderland,['Lewis Carroll'],1865
323,The Hobbit,['J.R.R. Tolkien'],1937
332,Harry Potter and the Philosopher's Stone,['J. K. Rowling'],1997

In [9]:
print("Duplicate titles in API:",
      api_clean.duplicated(subset=["title_clean"]).sum())

print("Duplicate titles in scraped data:",
      scraped_clean.duplicated(subset=["title_clean"]).sum())

Duplicate titles in API: 1021
Duplicate titles in scraped data: 0

In [10]:
api_clean = api_clean.drop_duplicates(
    subset=["title_clean"]
).copy()

scraped_clean = scraped_clean.drop_duplicates(
    subset=["title_clean"]
).copy()

print("API shape:", api_clean.shape)
print("Scraped shape:", scraped_clean.shape)

API shape: (1979, 10)
Scraped shape: (169, 10)

In [11]:
merged_df = pd.merge(
    api_clean,
    scraped_clean,
    on="title_clean",
    how="inner",
    suffixes=("_api", "_scraped")
)

print("Merged dataset shape:", merged_df.shape)

display(merged_df.head())

Merged dataset shape: (55, 19)

,author_name,edition_count,first_publish_year,key,number_of_pages_median,title_api,ratings_average,ratings_count,genre,title_clean,title_scraped,author,language,publication_year,decade,sales_millions,wiki_genre,genre_raw,sales_text
0,['Lewis Carroll'],3547,1865,/works/OL138052W,133.0,Alice's Adventures in Wonderland,4.043859,228.0,fantasy,alices adventures in wonderland,Alice's Adventures in Wonderland,Lewis Carroll,English,1865,1860,100.0,fantasy,"Fantasy, absurdist fiction",100 million
1,['Kenneth Grahame'],1346,1908,/works/OL28570037W,192.0,The Wind in the Willows,4.035714,56.0,fantasy,the wind in the willows,The Wind in the Willows,Kenneth Grahame,English,1908,1900,25.0,children's literature,Children's literature,25 million
2,['Lucy Maud Montgomery'],1299,1908,/works/OL77746W,309.0,Anne of Green Gables,4.284314,102.0,fantasy,anne of green gables,Anne of Green Gables,Lucy Maud Montgomery,English,1908,1900,50.0,children's novel,Children's novel,50 million
3,['J.R.R. Tolkien'],482,1937,/works/OL27482W,310.0,The Hobbit,4.290000,500.0,fantasy,the hobbit,The Hobbit,J. R. R. Tolkien,English,1937,1930,100.0,fantasy,"Fantasy, children's fiction",100 million
4,['J. K. Rowling'],400,1997,/works/OL82563W,302.0,Harry Potter and the Philosopher's Stone,4.221053,1045.0,fantasy,harry potter and the philosophers stone,Harry Potter and the Philosopher's Stone,J. K. Rowling,English,1997,1990,120.0,fantasy,Fantasy,120 million

In [12]:
merged_df["year_match"] = (
    merged_df["first_publish_year"] == merged_df["publication_year"]
)

print("Matching years:", merged_df["year_match"].sum())
print("Different years:", (~merged_df["year_match"]).sum())

display(
    merged_df.loc[
        ~merged_df["year_match"],
        [
            "title_api",
            "first_publish_year",
            "publication_year",
            "author_name",
            "author"
        ]
    ]
)

Matching years: 43
Different years: 12

,title_api,first_publish_year,publication_year,author_name,author
25,The Great Gatsby,1920,1925,['F. Scott Fitzgerald'],F. Scott Fitzgerald
27,Lolita,1777,1955,['Vladimir Nabokov'],Vladimir Nabokov
29,Paul et Virginie,1789,1788,['Bernardin de Saint-Pierre'],Jacques-Henri Bernardin de Saint-Pierre
30,Fifty Shades of Grey,2000,2011,['E. L. James'],E. L. James
37,Jaws,1973,1974,['Peter Benchley'],Peter Benchley
38,Adventures of Huckleberry Finn,1876,1885,['Mark Twain'],Mark Twain
39,A Tale of Two Cities,1800,1859,['Charles Dickens'],Charles Dickens
40,War and Peace,1845,1869,['Лев Толстой'],Leo Tolstoy
42,Heidi,1885,1880,"['Spyri, Johanna']",Johanna Spyri
45,The Book Thief,1998,2005,['Markus Zusak'],Markus Zusak
50,Tuesdays with Morrie,1994,1997,['Mitch Albom'],Mitch Albom
52,Wild Swans,1989,1992,['Jung Chang'],Jung Chang

In [13]:
merged_df["year"] = merged_df["publication_year"]

print(
    merged_df[
        ["title_api", "first_publish_year", "publication_year", "year"]
    ].head(10)
)

                                  title_api  first_publish_year  \
0          Alice's Adventures in Wonderland                1865
1                   The Wind in the Willows                1908
2                      Anne of Green Gables                1908
3                                The Hobbit                1937
4  Harry Potter and the Philosopher's Stone                1997
5   Harry Potter and the Chamber of Secrets                1998
6         Charlie and the Chocolate Factory                1964
7                           Charlotte's Web                1952
8                                   Matilda                1988
9                 James and the Giant Peach                1961

   publication_year  year
0              1865  1865
1              1908  1908
2              1908  1908
3              1937  1937
4              1997  1997
5              1998  1998
6              1964  1964
7              1952  1952
8              1988  1988
9              1961  1961

In [14]:
print("Missing values in merged dataset:")
print(merged_df.isnull().sum())

print("\nDuplicate titles:")
print(merged_df.duplicated(subset=["title_clean"]).sum())

print("\nFinal shape:")
print(merged_df.shape)

Missing values in merged dataset:
author_name               0
edition_count             0
first_publish_year        0
key                       0
number_of_pages_median    0
title_api                 0
ratings_average           0
ratings_count             0
genre                     0
title_clean               0
title_scraped             0
author                    0
language                  0
publication_year          0
decade                    0
sales_millions            0
wiki_genre                0
genre_raw                 0
sales_text                0
year_match                0
year                      0
dtype: int64

Duplicate titles:
0

Final shape:
(55, 21)

In [15]:
final_df = merged_df[
    [
        "title_scraped",
        "author",
        "year",
        "language",
        "genre",
        "wiki_genre",
        "number_of_pages_median",
        "edition_count",
        "ratings_average",
        "ratings_count",
        "sales_millions",
        "decade"
    ]
].copy()

final_df = final_df.rename(
    columns={
        "title_scraped": "title",
        "number_of_pages_median": "pages",
        "genre": "api_genre"
    }
)

display(final_df.head())

print("Final dataset shape:", final_df.shape)

,title,author,year,language,api_genre,wiki_genre,pages,edition_count,ratings_average,ratings_count,sales_millions,decade
0,Alice's Adventures in Wonderland,Lewis Carroll,1865,English,fantasy,fantasy,133.0,3547,4.043859,228.0,100.0,1860
1,The Wind in the Willows,Kenneth Grahame,1908,English,fantasy,children's literature,192.0,1346,4.035714,56.0,25.0,1900
2,Anne of Green Gables,Lucy Maud Montgomery,1908,English,fantasy,children's novel,309.0,1299,4.284314,102.0,50.0,1900
3,The Hobbit,J. R. R. Tolkien,1937,English,fantasy,fantasy,310.0,482,4.290000,500.0,100.0,1930
4,Harry Potter and the Philosopher's Stone,J. K. Rowling,1997,English,fantasy,fantasy,302.0,400,4.221053,1045.0,120.0,1990

Final dataset shape: (55, 12)

In [16]:
print("Missing values:")
print(final_df.isnull().sum())

print("\nDuplicates:", final_df.duplicated().sum())

print("\nData types:")
print(final_df.dtypes)

print("\nFinal shape:", final_df.shape)

Missing values:
title              0
author             0
year               0
language           0
api_genre          0
wiki_genre         0
pages              0
edition_count      0
ratings_average    0
ratings_count      0
sales_millions     0
decade             0
dtype: int64

Duplicates: 0

Data types:
title               object
author              object
year                 int64
language            object
api_genre           object
wiki_genre          object
pages              float64
edition_count        int64
ratings_average    float64
ratings_count      float64
sales_millions     float64
decade               int64
dtype: object

Final shape: (55, 12)

In [17]:
final_df.to_csv("books_merged_clean.csv", index=False)

print("Saved: books_merged_clean.csv")

Saved: books_merged_clean.csv